name: codersquare ci

on:
  push:
    branches: [ master ]

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build and run docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zaher1307/codersquare
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  test_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run code tests
      uses: actions/setup-node@v3
      with: 
        node-version: 16
    - run: |
        npm install
        npm ci
        npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run linter
      uses: synergy-au/eslint-action@v1
      with: 
        rules-path: './.github/workflows/.eslintrc.ci.js'
        setup-from-package-json: 'true'
